-- Code generated by github.com/primandproper/platform-go/v13/identity/internal/queriesgen. DO NOT EDIT.

-- name: CreateUser :exec
INSERT INTO identity_users (
	id,
	scope,
	username,
	email_address,
	first_name,
	last_name,
	hashed_password,
	requires_password_change,
	password_last_changed_at,
	two_factor_secret,
	two_factor_secret_verified_at,
	email_address_verified_at,
	email_address_verification_token,
	account_status,
	account_status_explanation,
	last_accepted_terms_of_service,
	last_accepted_privacy_policy
) VALUES (
	sqlc.arg(id),
	sqlc.arg(scope),
	sqlc.arg(username),
	sqlc.arg(email_address),
	sqlc.arg(first_name),
	sqlc.arg(last_name),
	sqlc.arg(hashed_password),
	sqlc.arg(requires_password_change),
	sqlc.narg(password_last_changed_at),
	sqlc.arg(two_factor_secret),
	sqlc.narg(two_factor_secret_verified_at),
	sqlc.narg(email_address_verified_at),
	sqlc.arg(email_address_verification_token),
	sqlc.arg(account_status),
	sqlc.arg(account_status_explanation),
	sqlc.narg(last_accepted_terms_of_service),
	sqlc.narg(last_accepted_privacy_policy)
);

-- name: GetUser :one
SELECT
	identity_users.id,
	identity_users.scope,
	identity_users.username,
	identity_users.email_address,
	identity_users.first_name,
	identity_users.last_name,
	identity_users.hashed_password,
	identity_users.requires_password_change,
	identity_users.password_last_changed_at,
	identity_users.two_factor_secret,
	identity_users.two_factor_secret_verified_at,
	identity_users.email_address_verified_at,
	identity_users.email_address_verification_token,
	identity_users.account_status,
	identity_users.account_status_explanation,
	identity_users.last_accepted_terms_of_service,
	identity_users.last_accepted_privacy_policy,
	identity_users.created_at,
	identity_users.last_updated_at,
	identity_users.archived_at
FROM identity_users
WHERE identity_users.archived_at IS NULL
	AND identity_users.id = sqlc.arg(id)
	AND identity_users.scope = sqlc.arg(scope);

-- name: ListUsers :many
SELECT
	identity_users.id,
	identity_users.scope,
	identity_users.username,
	identity_users.email_address,
	identity_users.first_name,
	identity_users.last_name,
	identity_users.hashed_password,
	identity_users.requires_password_change,
	identity_users.password_last_changed_at,
	identity_users.two_factor_secret,
	identity_users.two_factor_secret_verified_at,
	identity_users.email_address_verified_at,
	identity_users.email_address_verification_token,
	identity_users.account_status,
	identity_users.account_status_explanation,
	identity_users.last_accepted_terms_of_service,
	identity_users.last_accepted_privacy_policy,
	identity_users.created_at,
	identity_users.last_updated_at,
	identity_users.archived_at,
	(
		SELECT COUNT(identity_users.id)
		FROM identity_users
		WHERE identity_users.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND identity_users.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				identity_users.last_updated_at IS NULL
				OR identity_users.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				identity_users.last_updated_at IS NULL
				OR identity_users.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_users.archived_at IS NULL)
			AND identity_users.scope = sqlc.arg(scope)
	) AS filtered_count,
	(
		SELECT COUNT(identity_users.id)
		FROM identity_users
		WHERE (COALESCE(sqlc.narg(include_archived), false) = true OR identity_users.archived_at IS NULL)
			AND identity_users.scope = sqlc.arg(scope)
	) AS total_count
FROM identity_users
WHERE identity_users.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND identity_users.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		identity_users.last_updated_at IS NULL
		OR identity_users.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		identity_users.last_updated_at IS NULL
		OR identity_users.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_users.archived_at IS NULL)
	AND identity_users.scope = sqlc.arg(scope)
	AND identity_users.id > COALESCE(sqlc.narg(page_cursor), '')
ORDER BY identity_users.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: UpdateUser :execrows
UPDATE identity_users SET
	username = sqlc.arg(username),
	email_address = sqlc.arg(email_address),
	first_name = sqlc.arg(first_name),
	last_name = sqlc.arg(last_name),
	email_address_verified_at = sqlc.narg(email_address_verified_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND scope = sqlc.arg(scope);

-- name: ArchiveUser :execrows
UPDATE identity_users SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND scope = sqlc.arg(scope);

-- name: CreateAccount :exec
INSERT INTO identity_accounts (
	id,
	scope,
	name,
	owner_user_id,
	billing_status,
	subscription_plan_id,
	payment_processor_customer_id,
	last_payment_provider_synced_at,
	address_line1,
	address_line2,
	address_city,
	address_state,
	address_postal_code,
	address_country,
	address_phone,
	time_zone
) VALUES (
	sqlc.arg(id),
	sqlc.arg(scope),
	sqlc.arg(name),
	sqlc.arg(owner_user_id),
	sqlc.arg(billing_status),
	sqlc.narg(subscription_plan_id),
	sqlc.arg(payment_processor_customer_id),
	sqlc.narg(last_payment_provider_synced_at),
	sqlc.arg(address_line1),
	sqlc.arg(address_line2),
	sqlc.arg(address_city),
	sqlc.arg(address_state),
	sqlc.arg(address_postal_code),
	sqlc.arg(address_country),
	sqlc.arg(address_phone),
	sqlc.arg(time_zone)
);

-- name: GetAccount :one
SELECT
	identity_accounts.id,
	identity_accounts.scope,
	identity_accounts.name,
	identity_accounts.owner_user_id,
	identity_accounts.billing_status,
	identity_accounts.subscription_plan_id,
	identity_accounts.payment_processor_customer_id,
	identity_accounts.last_payment_provider_synced_at,
	identity_accounts.address_line1,
	identity_accounts.address_line2,
	identity_accounts.address_city,
	identity_accounts.address_state,
	identity_accounts.address_postal_code,
	identity_accounts.address_country,
	identity_accounts.address_phone,
	identity_accounts.time_zone,
	identity_accounts.created_at,
	identity_accounts.last_updated_at,
	identity_accounts.archived_at
FROM identity_accounts
WHERE identity_accounts.archived_at IS NULL
	AND identity_accounts.id = sqlc.arg(id)
	AND identity_accounts.scope = sqlc.arg(scope);

-- name: ListAccounts :many
SELECT
	identity_accounts.id,
	identity_accounts.scope,
	identity_accounts.name,
	identity_accounts.owner_user_id,
	identity_accounts.billing_status,
	identity_accounts.subscription_plan_id,
	identity_accounts.payment_processor_customer_id,
	identity_accounts.last_payment_provider_synced_at,
	identity_accounts.address_line1,
	identity_accounts.address_line2,
	identity_accounts.address_city,
	identity_accounts.address_state,
	identity_accounts.address_postal_code,
	identity_accounts.address_country,
	identity_accounts.address_phone,
	identity_accounts.time_zone,
	identity_accounts.created_at,
	identity_accounts.last_updated_at,
	identity_accounts.archived_at,
	(
		SELECT COUNT(identity_accounts.id)
		FROM identity_accounts
		WHERE identity_accounts.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND identity_accounts.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				identity_accounts.last_updated_at IS NULL
				OR identity_accounts.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				identity_accounts.last_updated_at IS NULL
				OR identity_accounts.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_accounts.archived_at IS NULL)
			AND identity_accounts.scope = sqlc.arg(scope)
	) AS filtered_count,
	(
		SELECT COUNT(identity_accounts.id)
		FROM identity_accounts
		WHERE (COALESCE(sqlc.narg(include_archived), false) = true OR identity_accounts.archived_at IS NULL)
			AND identity_accounts.scope = sqlc.arg(scope)
	) AS total_count
FROM identity_accounts
WHERE identity_accounts.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND identity_accounts.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		identity_accounts.last_updated_at IS NULL
		OR identity_accounts.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		identity_accounts.last_updated_at IS NULL
		OR identity_accounts.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_accounts.archived_at IS NULL)
	AND identity_accounts.scope = sqlc.arg(scope)
	AND identity_accounts.id > COALESCE(sqlc.narg(page_cursor), '')
ORDER BY identity_accounts.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: UpdateAccount :execrows
UPDATE identity_accounts SET
	name = sqlc.arg(name),
	address_line1 = sqlc.arg(address_line1),
	address_line2 = sqlc.arg(address_line2),
	address_city = sqlc.arg(address_city),
	address_state = sqlc.arg(address_state),
	address_postal_code = sqlc.arg(address_postal_code),
	address_country = sqlc.arg(address_country),
	address_phone = sqlc.arg(address_phone),
	time_zone = sqlc.arg(time_zone),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND scope = sqlc.arg(scope);

-- name: ArchiveAccount :execrows
UPDATE identity_accounts SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND scope = sqlc.arg(scope);

-- name: CreateInvitation :exec
INSERT INTO identity_invitations (
	id,
	scope,
	belongs_to_account,
	from_user,
	to_email,
	to_name,
	to_user,
	token,
	status,
	note,
	expires_at
) VALUES (
	sqlc.arg(id),
	sqlc.arg(scope),
	sqlc.arg(belongs_to_account),
	sqlc.arg(from_user),
	sqlc.arg(to_email),
	sqlc.arg(to_name),
	sqlc.narg(to_user),
	sqlc.arg(token),
	sqlc.arg(status),
	sqlc.arg(note),
	sqlc.arg(expires_at)
);

-- name: GetInvitation :one
SELECT
	identity_invitations.id,
	identity_invitations.scope,
	identity_invitations.belongs_to_account,
	identity_invitations.from_user,
	identity_invitations.to_email,
	identity_invitations.to_name,
	identity_invitations.to_user,
	identity_invitations.token,
	identity_invitations.status,
	identity_invitations.note,
	identity_invitations.expires_at,
	identity_invitations.created_at,
	identity_invitations.last_updated_at,
	identity_invitations.archived_at
FROM identity_invitations
WHERE identity_invitations.archived_at IS NULL
	AND identity_invitations.id = sqlc.arg(id)
	AND identity_invitations.scope = sqlc.arg(scope);

-- name: ListInvitations :many
SELECT
	identity_invitations.id,
	identity_invitations.scope,
	identity_invitations.belongs_to_account,
	identity_invitations.from_user,
	identity_invitations.to_email,
	identity_invitations.to_name,
	identity_invitations.to_user,
	identity_invitations.token,
	identity_invitations.status,
	identity_invitations.note,
	identity_invitations.expires_at,
	identity_invitations.created_at,
	identity_invitations.last_updated_at,
	identity_invitations.archived_at,
	(
		SELECT COUNT(identity_invitations.id)
		FROM identity_invitations
		WHERE identity_invitations.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND identity_invitations.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				identity_invitations.last_updated_at IS NULL
				OR identity_invitations.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				identity_invitations.last_updated_at IS NULL
				OR identity_invitations.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_invitations.archived_at IS NULL)
			AND identity_invitations.scope = sqlc.arg(scope)
	) AS filtered_count,
	(
		SELECT COUNT(identity_invitations.id)
		FROM identity_invitations
		WHERE (COALESCE(sqlc.narg(include_archived), false) = true OR identity_invitations.archived_at IS NULL)
			AND identity_invitations.scope = sqlc.arg(scope)
	) AS total_count
FROM identity_invitations
WHERE identity_invitations.created_at > COALESCE(sqlc.narg(created_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND identity_invitations.created_at < COALESCE(sqlc.narg(created_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		identity_invitations.last_updated_at IS NULL
		OR identity_invitations.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		identity_invitations.last_updated_at IS NULL
		OR identity_invitations.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(sqlc.narg(include_archived), false) = true OR identity_invitations.archived_at IS NULL)
	AND identity_invitations.scope = sqlc.arg(scope)
	AND identity_invitations.id > COALESCE(sqlc.narg(page_cursor), '')
ORDER BY identity_invitations.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);
