// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// DBTX is what a generated method needs from a database handle.
//
// It is satisfied by *sql.DB, *sql.Tx, and *sql.Conn alike, and it is taken per
// call rather than held on the querier so that running a query inside a
// transaction is a different argument rather than a different querier.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// Dialect names a SQL dialect this package was generated for.
//
// It is a type rather than a string so that naming one that was not generated
// is a compile error rather than an error value at startup.
type Dialect string

const (
	// DialectMySQL is mysql.
	DialectMySQL Dialect = "mysql"
	// DialectPostgreSQL is postgresql.
	DialectPostgreSQL Dialect = "postgresql"
	// DialectSQLite is sqlite.
	DialectSQLite Dialect = "sqlite"
)

// Dialects lists every dialect this package was generated for, in a stable
// order.
func Dialects() []Dialect {
	return []Dialect{
		DialectMySQL,
		DialectPostgreSQL,
		DialectSQLite,
	}
}

// prefixMarker stands where a table name begins in every statement below.
//
// The generator placed it using the analyzer's catalog, so it marks identifiers
// that are genuinely tables rather than words that look like them. New replaces
// it once per statement, at construction; nothing rewrites SQL at query time.
const prefixMarker = "{{prefix}}"

// slicePlaceholders renders what one list parameter expands to: a placeholder
// per element, comma-separated.
//
// An empty list renders NULL rather than nothing, because `IN ()` is a syntax
// error on MySQL and SQLite both. `IN (NULL)` is the predicate that matches no
// row, which is the same answer Postgres gives when an empty array is bound to
// `= ANY` — so an empty list means the same thing on every dialect here.
func slicePlaceholders(placeholder string, n int) string {
	if n == 0 {
		return "NULL"
	}

	return strings.TrimPrefix(strings.Repeat(","+placeholder, n), ",")
}

// New returns the Querier for a dialect, with every table name prefixed.
//
// Every dialect in the roster is compiled into this package; a caller
// instantiates the one their database speaks. The prefix is substituted into
// each statement once, here, and the statements are held ready to run.
func New(dialect Dialect, prefix string) (Querier, error) {
	switch dialect {
	case DialectMySQL:
		return newMySQL(prefix), nil
	case DialectPostgreSQL:
		return newPostgreSQL(prefix), nil
	case DialectSQLite:
		return newSQLite(prefix), nil
	default:
		return nil, fmt.Errorf("identitydb: unknown dialect %q", dialect)
	}
}
