// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
//
// # A note on empty lists
//
// A list parameter that is empty matches nothing, on every dialect: Postgres
// binds an empty array to `= ANY`, and the other two expand to `IN (NULL)` because
// `IN ()` is a syntax error there. Asking for the rows whose key is in an empty
// set gets no rows back, which is what the empty set says, so a caller does not
// have to guard the call.
//
// The negation is where they part company, and nothing below can warn you. An
// empty list makes `NOT IN (NULL)` never true, so it matches nothing, while
// Postgres's empty `<> ALL` is true and matches everything. Both readings are
// defensible and no shared signature can say which was meant — so test
// membership rather than its negation, and let the caller decide what an empty
// set means before it calls.
type Querier interface {
	// ArchiveAccount runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveAccount(ctx context.Context, db DBTX, arg ArchiveAccountParams) (int64, error)
	// ArchiveUser runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveUser(ctx context.Context, db DBTX, arg ArchiveUserParams) (int64, error)
	// AssignUserRole runs the :exec query.
	AssignUserRole(ctx context.Context, db DBTX, arg AssignUserRoleParams) error
	// CreateAccount runs the :exec query.
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error
	// CreateInvitation runs the :exec query.
	CreateInvitation(ctx context.Context, db DBTX, arg CreateInvitationParams) error
	// CreateUser runs the :exec query.
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	// GetAccount runs the :one query.
	GetAccount(ctx context.Context, db DBTX, arg GetAccountParams) (GetAccountRow, error)
	// GetInvitation runs the :one query.
	GetInvitation(ctx context.Context, db DBTX, arg GetInvitationParams) (GetInvitationRow, error)
	// GetUser runs the :one query.
	GetUser(ctx context.Context, db DBTX, arg GetUserParams) (GetUserRow, error)
	// ListAccounts runs the :many query.
	ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]ListAccountsRow, error)
	// ListInvitations runs the :many query.
	ListInvitations(ctx context.Context, db DBTX, arg ListInvitationsParams) ([]ListInvitationsRow, error)
	// ListRolesForUsers runs the :many query.
	ListRolesForUsers(ctx context.Context, db DBTX, arg ListRolesForUsersParams) ([]ListRolesForUsersRow, error)
	// ListUsers runs the :many query.
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error)
	// UpdateAccount runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (int64, error)
	// UpdateUser runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (int64, error)
}
