// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"context"
	"strings"
	"time"
)

const archiveAccountPostgreSQL = `UPDATE {{prefix}}identity_accounts SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $1
	AND scope = $2`

const archiveUserPostgreSQL = `UPDATE {{prefix}}identity_users SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $1
	AND scope = $2`

const assignUserRolePostgreSQL = `INSERT INTO {{prefix}}identity_user_roles (
	user_id,
	role
) VALUES (
	$1,
	$2
)`

const createAccountPostgreSQL = `INSERT INTO {{prefix}}identity_accounts (
	id,
	scope,
	name,
	owner_user_id,
	billing_status,
	subscription_plan_id,
	payment_processor_customer_id,
	last_payment_provider_synced_at,
	address_line1,
	address_line2,
	address_city,
	address_state,
	address_postal_code,
	address_country,
	address_phone,
	time_zone
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16
)`

const createInvitationPostgreSQL = `INSERT INTO {{prefix}}identity_invitations (
	id,
	scope,
	belongs_to_account,
	from_user,
	to_email,
	to_name,
	to_user,
	token,
	status,
	note,
	expires_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11
)`

const createUserPostgreSQL = `
INSERT INTO {{prefix}}identity_users (
	id,
	scope,
	username,
	email_address,
	first_name,
	last_name,
	hashed_password,
	requires_password_change,
	password_last_changed_at,
	two_factor_secret,
	two_factor_secret_verified_at,
	email_address_verified_at,
	email_address_verification_token,
	account_status,
	account_status_explanation,
	last_accepted_terms_of_service,
	last_accepted_privacy_policy
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12,
	$13,
	$14,
	$15,
	$16,
	$17
)`

const getAccountPostgreSQL = `SELECT
	{{prefix}}identity_accounts.id,
	{{prefix}}identity_accounts.scope,
	{{prefix}}identity_accounts.name,
	{{prefix}}identity_accounts.owner_user_id,
	{{prefix}}identity_accounts.billing_status,
	{{prefix}}identity_accounts.subscription_plan_id,
	{{prefix}}identity_accounts.payment_processor_customer_id,
	{{prefix}}identity_accounts.last_payment_provider_synced_at,
	{{prefix}}identity_accounts.address_line1,
	{{prefix}}identity_accounts.address_line2,
	{{prefix}}identity_accounts.address_city,
	{{prefix}}identity_accounts.address_state,
	{{prefix}}identity_accounts.address_postal_code,
	{{prefix}}identity_accounts.address_country,
	{{prefix}}identity_accounts.address_phone,
	{{prefix}}identity_accounts.time_zone,
	{{prefix}}identity_accounts.created_at,
	{{prefix}}identity_accounts.last_updated_at,
	{{prefix}}identity_accounts.archived_at
FROM {{prefix}}identity_accounts
WHERE {{prefix}}identity_accounts.archived_at IS NULL
	AND {{prefix}}identity_accounts.id = $1
	AND {{prefix}}identity_accounts.scope = $2`

const getInvitationPostgreSQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.archived_at IS NULL
	AND {{prefix}}identity_invitations.id = $1
	AND {{prefix}}identity_invitations.scope = $2`

const getUserPostgreSQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.id = $1
	AND {{prefix}}identity_users.scope = $2`

const listAccountsPostgreSQL = `SELECT
	{{prefix}}identity_accounts.id,
	{{prefix}}identity_accounts.scope,
	{{prefix}}identity_accounts.name,
	{{prefix}}identity_accounts.owner_user_id,
	{{prefix}}identity_accounts.billing_status,
	{{prefix}}identity_accounts.subscription_plan_id,
	{{prefix}}identity_accounts.payment_processor_customer_id,
	{{prefix}}identity_accounts.last_payment_provider_synced_at,
	{{prefix}}identity_accounts.address_line1,
	{{prefix}}identity_accounts.address_line2,
	{{prefix}}identity_accounts.address_city,
	{{prefix}}identity_accounts.address_state,
	{{prefix}}identity_accounts.address_postal_code,
	{{prefix}}identity_accounts.address_country,
	{{prefix}}identity_accounts.address_phone,
	{{prefix}}identity_accounts.time_zone,
	{{prefix}}identity_accounts.created_at,
	{{prefix}}identity_accounts.last_updated_at,
	{{prefix}}identity_accounts.archived_at,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		WHERE {{prefix}}identity_accounts.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}identity_accounts.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}identity_accounts.last_updated_at IS NULL
				OR {{prefix}}identity_accounts.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_accounts.id)
		FROM {{prefix}}identity_accounts
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}identity_accounts.archived_at IS NULL)
			AND {{prefix}}identity_accounts.scope = $6
	) AS total_count
FROM {{prefix}}identity_accounts
WHERE {{prefix}}identity_accounts.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}identity_accounts.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}identity_accounts.last_updated_at IS NULL
		OR {{prefix}}identity_accounts.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}identity_accounts.archived_at IS NULL)
	AND {{prefix}}identity_accounts.scope = $6
	AND {{prefix}}identity_accounts.id > COALESCE($7, '')
ORDER BY {{prefix}}identity_accounts.id ASC
LIMIT COALESCE($8, 50)`

const listInvitationsPostgreSQL = `SELECT
	{{prefix}}identity_invitations.id,
	{{prefix}}identity_invitations.scope,
	{{prefix}}identity_invitations.belongs_to_account,
	{{prefix}}identity_invitations.from_user,
	{{prefix}}identity_invitations.to_email,
	{{prefix}}identity_invitations.to_name,
	{{prefix}}identity_invitations.to_user,
	{{prefix}}identity_invitations.token,
	{{prefix}}identity_invitations.status,
	{{prefix}}identity_invitations.note,
	{{prefix}}identity_invitations.expires_at,
	{{prefix}}identity_invitations.created_at,
	{{prefix}}identity_invitations.last_updated_at,
	{{prefix}}identity_invitations.archived_at,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE {{prefix}}identity_invitations.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}identity_invitations.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}identity_invitations.last_updated_at IS NULL
				OR {{prefix}}identity_invitations.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_invitations.id)
		FROM {{prefix}}identity_invitations
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}identity_invitations.archived_at IS NULL)
			AND {{prefix}}identity_invitations.scope = $6
	) AS total_count
FROM {{prefix}}identity_invitations
WHERE {{prefix}}identity_invitations.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}identity_invitations.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}identity_invitations.last_updated_at IS NULL
		OR {{prefix}}identity_invitations.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}identity_invitations.archived_at IS NULL)
	AND {{prefix}}identity_invitations.scope = $6
	AND {{prefix}}identity_invitations.id > COALESCE($7, '')
ORDER BY {{prefix}}identity_invitations.id ASC
LIMIT COALESCE($8, 50)`

const listRolesForUsersPostgreSQL = `SELECT
	{{prefix}}identity_user_roles.user_id,
	{{prefix}}identity_user_roles.role
FROM {{prefix}}identity_user_roles
	JOIN {{prefix}}identity_users ON {{prefix}}identity_users.id = {{prefix}}identity_user_roles.user_id
WHERE {{prefix}}identity_users.archived_at IS NULL
	AND {{prefix}}identity_users.scope = $1
	AND {{prefix}}identity_user_roles.user_id = ANY($2::TEXT[])
ORDER BY {{prefix}}identity_user_roles.user_id ASC, {{prefix}}identity_user_roles.role ASC`

const listUsersPostgreSQL = `SELECT
	{{prefix}}identity_users.id,
	{{prefix}}identity_users.scope,
	{{prefix}}identity_users.username,
	{{prefix}}identity_users.email_address,
	{{prefix}}identity_users.first_name,
	{{prefix}}identity_users.last_name,
	{{prefix}}identity_users.hashed_password,
	{{prefix}}identity_users.requires_password_change,
	{{prefix}}identity_users.password_last_changed_at,
	{{prefix}}identity_users.two_factor_secret,
	{{prefix}}identity_users.two_factor_secret_verified_at,
	{{prefix}}identity_users.email_address_verified_at,
	{{prefix}}identity_users.email_address_verification_token,
	{{prefix}}identity_users.account_status,
	{{prefix}}identity_users.account_status_explanation,
	{{prefix}}identity_users.last_accepted_terms_of_service,
	{{prefix}}identity_users.last_accepted_privacy_policy,
	{{prefix}}identity_users.created_at,
	{{prefix}}identity_users.last_updated_at,
	{{prefix}}identity_users.archived_at,
	(
		SELECT COUNT({{prefix}}identity_users.id)
		FROM {{prefix}}identity_users
		WHERE {{prefix}}identity_users.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}identity_users.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}identity_users.last_updated_at IS NULL
				OR {{prefix}}identity_users.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}identity_users.last_updated_at IS NULL
				OR {{prefix}}identity_users.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}identity_users.archived_at IS NULL)
			AND {{prefix}}identity_users.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}identity_users.id)
		FROM {{prefix}}identity_users
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}identity_users.archived_at IS NULL)
			AND {{prefix}}identity_users.scope = $6
	) AS total_count
FROM {{prefix}}identity_users
WHERE {{prefix}}identity_users.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}identity_users.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}identity_users.last_updated_at IS NULL
		OR {{prefix}}identity_users.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}identity_users.last_updated_at IS NULL
		OR {{prefix}}identity_users.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}identity_users.archived_at IS NULL)
	AND {{prefix}}identity_users.scope = $6
	AND {{prefix}}identity_users.id > COALESCE($7, '')
ORDER BY {{prefix}}identity_users.id ASC
LIMIT COALESCE($8, 50)`

const updateAccountPostgreSQL = `UPDATE {{prefix}}identity_accounts SET
	name = $1,
	address_line1 = $2,
	address_line2 = $3,
	address_city = $4,
	address_state = $5,
	address_postal_code = $6,
	address_country = $7,
	address_phone = $8,
	time_zone = $9,
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $10
	AND scope = $11`

const updateUserPostgreSQL = `UPDATE {{prefix}}identity_users SET
	username = $1,
	email_address = $2,
	first_name = $3,
	last_name = $4,
	email_address_verified_at = $5,
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $6
	AND scope = $7`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	archiveAccount    string
	archiveUser       string
	assignUserRole    string
	createAccount     string
	createInvitation  string
	createUser        string
	getAccount        string
	getInvitation     string
	getUser           string
	listAccounts      string
	listInvitations   string
	listRolesForUsers string
	listUsers         string
	updateAccount     string
	updateUser        string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		archiveAccount:    strings.ReplaceAll(archiveAccountPostgreSQL, prefixMarker, prefix),
		archiveUser:       strings.ReplaceAll(archiveUserPostgreSQL, prefixMarker, prefix),
		assignUserRole:    strings.ReplaceAll(assignUserRolePostgreSQL, prefixMarker, prefix),
		createAccount:     strings.ReplaceAll(createAccountPostgreSQL, prefixMarker, prefix),
		createInvitation:  strings.ReplaceAll(createInvitationPostgreSQL, prefixMarker, prefix),
		createUser:        strings.ReplaceAll(createUserPostgreSQL, prefixMarker, prefix),
		getAccount:        strings.ReplaceAll(getAccountPostgreSQL, prefixMarker, prefix),
		getInvitation:     strings.ReplaceAll(getInvitationPostgreSQL, prefixMarker, prefix),
		getUser:           strings.ReplaceAll(getUserPostgreSQL, prefixMarker, prefix),
		listAccounts:      strings.ReplaceAll(listAccountsPostgreSQL, prefixMarker, prefix),
		listInvitations:   strings.ReplaceAll(listInvitationsPostgreSQL, prefixMarker, prefix),
		listRolesForUsers: strings.ReplaceAll(listRolesForUsersPostgreSQL, prefixMarker, prefix),
		listUsers:         strings.ReplaceAll(listUsersPostgreSQL, prefixMarker, prefix),
		updateAccount:     strings.ReplaceAll(updateAccountPostgreSQL, prefixMarker, prefix),
		updateUser:        strings.ReplaceAll(updateUserPostgreSQL, prefixMarker, prefix),
	}
}

// ArchiveAccount runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveAccount(ctx context.Context, db DBTX, arg ArchiveAccountParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveAccount,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ArchiveUser runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveUser(ctx context.Context, db DBTX, arg ArchiveUserParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveUser,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// AssignUserRole runs the :exec query against postgresql.
func (q *postgresqlQueries) AssignUserRole(ctx context.Context, db DBTX, arg AssignUserRoleParams) error {
	_, err := db.ExecContext(ctx, q.assignUserRole,
		arg.UserID,
		arg.Role,
	)

	return err
}

// CreateAccount runs the :exec query against postgresql.
func (q *postgresqlQueries) CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error {
	_, err := db.ExecContext(ctx, q.createAccount,
		arg.ID,
		arg.Scope,
		arg.Name,
		arg.OwnerUserID,
		arg.BillingStatus,
		arg.SubscriptionPlanID,
		arg.PaymentProcessorCustomerID,
		arg.LastPaymentProviderSyncedAt,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.AddressPhone,
		arg.TimeZone,
	)

	return err
}

// CreateInvitation runs the :exec query against postgresql.
func (q *postgresqlQueries) CreateInvitation(ctx context.Context, db DBTX, arg CreateInvitationParams) error {
	_, err := db.ExecContext(ctx, q.createInvitation,
		arg.ID,
		arg.Scope,
		arg.BelongsToAccount,
		arg.FromUser,
		arg.ToEmail,
		arg.ToName,
		arg.ToUser,
		arg.Token,
		arg.Status,
		arg.Note,
		arg.ExpiresAt,
	)

	return err
}

// CreateUser runs the :exec query against postgresql.
func (q *postgresqlQueries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error {
	_, err := db.ExecContext(ctx, q.createUser,
		arg.ID,
		arg.Scope,
		arg.Username,
		arg.EmailAddress,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.RequiresPasswordChange,
		arg.PasswordLastChangedAt,
		arg.TwoFactorSecret,
		arg.TwoFactorSecretVerifiedAt,
		arg.EmailAddressVerifiedAt,
		arg.EmailAddressVerificationToken,
		arg.AccountStatus,
		arg.AccountStatusExplanation,
		arg.LastAcceptedTermsOfService,
		arg.LastAcceptedPrivacyPolicy,
	)

	return err
}

// GetAccount runs the :one query against postgresql.
func (q *postgresqlQueries) GetAccount(ctx context.Context, db DBTX, arg GetAccountParams) (GetAccountRow, error) {
	row := db.QueryRowContext(ctx, q.getAccount,
		arg.ID,
		arg.Scope,
	)

	var i GetAccountRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Name,
		&i.OwnerUserID,
		&i.BillingStatus,
		&i.SubscriptionPlanID,
		&i.PaymentProcessorCustomerID,
		&i.LastPaymentProviderSyncedAt,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressPostalCode,
		&i.AddressCountry,
		&i.AddressPhone,
		&i.TimeZone,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetInvitation runs the :one query against postgresql.
func (q *postgresqlQueries) GetInvitation(ctx context.Context, db DBTX, arg GetInvitationParams) (GetInvitationRow, error) {
	row := db.QueryRowContext(ctx, q.getInvitation,
		arg.ID,
		arg.Scope,
	)

	var i GetInvitationRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToAccount,
		&i.FromUser,
		&i.ToEmail,
		&i.ToName,
		&i.ToUser,
		&i.Token,
		&i.Status,
		&i.Note,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetUser runs the :one query against postgresql.
func (q *postgresqlQueries) GetUser(ctx context.Context, db DBTX, arg GetUserParams) (GetUserRow, error) {
	row := db.QueryRowContext(ctx, q.getUser,
		arg.ID,
		arg.Scope,
	)

	var i GetUserRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Username,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.RequiresPasswordChange,
		&i.PasswordLastChangedAt,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretVerifiedAt,
		&i.EmailAddressVerifiedAt,
		&i.EmailAddressVerificationToken,
		&i.AccountStatus,
		&i.AccountStatusExplanation,
		&i.LastAcceptedTermsOfService,
		&i.LastAcceptedPrivacyPolicy,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// ListAccounts runs the :many query against postgresql.
func (q *postgresqlQueries) ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := db.QueryContext(ctx, q.listAccounts,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListAccountsRow

	for rows.Next() {
		var i ListAccountsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Name,
			&i.OwnerUserID,
			&i.BillingStatus,
			&i.SubscriptionPlanID,
			&i.PaymentProcessorCustomerID,
			&i.LastPaymentProviderSyncedAt,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressPostalCode,
			&i.AddressCountry,
			&i.AddressPhone,
			&i.TimeZone,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListInvitations runs the :many query against postgresql.
func (q *postgresqlQueries) ListInvitations(ctx context.Context, db DBTX, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := db.QueryContext(ctx, q.listInvitations,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListInvitationsRow

	for rows.Next() {
		var i ListInvitationsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToAccount,
			&i.FromUser,
			&i.ToEmail,
			&i.ToName,
			&i.ToUser,
			&i.Token,
			&i.Status,
			&i.Note,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRolesForUsers runs the :many query against postgresql.
func (q *postgresqlQueries) ListRolesForUsers(ctx context.Context, db DBTX, arg ListRolesForUsersParams) ([]ListRolesForUsersRow, error) {
	rows, err := db.QueryContext(ctx, q.listRolesForUsers,
		arg.Scope,
		arg.UserIDs,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolesForUsersRow

	for rows.Next() {
		var i ListRolesForUsersRow

		if err := rows.Scan(
			&i.UserID,
			&i.Role,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListUsers runs the :many query against postgresql.
func (q *postgresqlQueries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := db.QueryContext(ctx, q.listUsers,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListUsersRow

	for rows.Next() {
		var i ListUsersRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Username,
			&i.EmailAddress,
			&i.FirstName,
			&i.LastName,
			&i.HashedPassword,
			&i.RequiresPasswordChange,
			&i.PasswordLastChangedAt,
			&i.TwoFactorSecret,
			&i.TwoFactorSecretVerifiedAt,
			&i.EmailAddressVerifiedAt,
			&i.EmailAddressVerificationToken,
			&i.AccountStatus,
			&i.AccountStatusExplanation,
			&i.LastAcceptedTermsOfService,
			&i.LastAcceptedPrivacyPolicy,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// UpdateAccount runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateAccount,
		arg.Name,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressPostalCode,
		arg.AddressCountry,
		arg.AddressPhone,
		arg.TimeZone,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateUser runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateUser,
		arg.Username,
		arg.EmailAddress,
		arg.FirstName,
		arg.LastName,
		arg.EmailAddressVerifiedAt,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID    string
		Scope string
	}(ArchiveAccountParams{})
	_ = struct {
		ID    string
		Scope string
	}(ArchiveUserParams{})
	_ = struct {
		UserID string
		Role   string
	}(AssignUserRoleParams{})
	_ = struct {
		ID                          string
		Scope                       string
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
	}(CreateAccountParams{})
	_ = struct {
		ID               string
		Scope            string
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
	}(CreateInvitationParams{})
	_ = struct {
		ID                            string
		Scope                         string
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
	}(CreateUserParams{})
	_ = struct {
		ID    string
		Scope string
	}(GetAccountParams{})
	_ = struct {
		ID                          string
		Scope                       string
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
		CreatedAt                   time.Time
		LastUpdatedAt               *time.Time
		ArchivedAt                  *time.Time
	}(GetAccountRow{})
	_ = struct {
		ID    string
		Scope string
	}(GetInvitationParams{})
	_ = struct {
		ID               string
		Scope            string
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
	}(GetInvitationRow{})
	_ = struct {
		ID    string
		Scope string
	}(GetUserParams{})
	_ = struct {
		ID                            string
		Scope                         string
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
	}(GetUserRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           string
		PageCursor      *string
		ResultLimit     int64
	}(ListAccountsParams{})
	_ = struct {
		ID                          string
		Scope                       string
		Name                        string
		OwnerUserID                 string
		BillingStatus               string
		SubscriptionPlanID          *string
		PaymentProcessorCustomerID  string
		LastPaymentProviderSyncedAt *time.Time
		AddressLine1                string
		AddressLine2                string
		AddressCity                 string
		AddressState                string
		AddressPostalCode           string
		AddressCountry              string
		AddressPhone                string
		TimeZone                    string
		CreatedAt                   time.Time
		LastUpdatedAt               *time.Time
		ArchivedAt                  *time.Time
		FilteredCount               int64
		TotalCount                  int64
	}(ListAccountsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           string
		PageCursor      *string
		ResultLimit     int64
	}(ListInvitationsParams{})
	_ = struct {
		ID               string
		Scope            string
		BelongsToAccount string
		FromUser         string
		ToEmail          string
		ToName           string
		ToUser           *string
		Token            string
		Status           string
		Note             string
		ExpiresAt        time.Time
		CreatedAt        time.Time
		LastUpdatedAt    *time.Time
		ArchivedAt       *time.Time
		FilteredCount    int64
		TotalCount       int64
	}(ListInvitationsRow{})
	_ = struct {
		Scope   string
		UserIDs []string
	}(ListRolesForUsersParams{})
	_ = struct {
		UserID string
		Role   string
	}(ListRolesForUsersRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           string
		PageCursor      *string
		ResultLimit     int64
	}(ListUsersParams{})
	_ = struct {
		ID                            string
		Scope                         string
		Username                      string
		EmailAddress                  string
		FirstName                     string
		LastName                      string
		HashedPassword                string
		RequiresPasswordChange        bool
		PasswordLastChangedAt         *time.Time
		TwoFactorSecret               string
		TwoFactorSecretVerifiedAt     *time.Time
		EmailAddressVerifiedAt        *time.Time
		EmailAddressVerificationToken string
		AccountStatus                 string
		AccountStatusExplanation      string
		LastAcceptedTermsOfService    *time.Time
		LastAcceptedPrivacyPolicy     *time.Time
		CreatedAt                     time.Time
		LastUpdatedAt                 *time.Time
		ArchivedAt                    *time.Time
		FilteredCount                 int64
		TotalCount                    int64
	}(ListUsersRow{})
	_ = struct {
		Name              string
		AddressLine1      string
		AddressLine2      string
		AddressCity       string
		AddressState      string
		AddressPostalCode string
		AddressCountry    string
		AddressPhone      string
		TimeZone          string
		ID                string
		Scope             string
	}(UpdateAccountParams{})
	_ = struct {
		Username               string
		EmailAddress           string
		FirstName              string
		LastName               string
		EmailAddressVerifiedAt *time.Time
		ID                     string
		Scope                  string
	}(UpdateUserParams{})
)
