// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: dev

package identitydb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
type Querier interface {
	// ArchiveAccount runs the :execrows query.
	ArchiveAccount(ctx context.Context, db DBTX, arg ArchiveAccountParams) (int64, error)
	// ArchiveUser runs the :execrows query.
	ArchiveUser(ctx context.Context, db DBTX, arg ArchiveUserParams) (int64, error)
	// CreateAccount runs the :exec query.
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) error
	// CreateInvitation runs the :exec query.
	CreateInvitation(ctx context.Context, db DBTX, arg CreateInvitationParams) error
	// CreateUser runs the :exec query.
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	// GetAccount runs the :one query.
	GetAccount(ctx context.Context, db DBTX, arg GetAccountParams) (GetAccountRow, error)
	// GetInvitation runs the :one query.
	GetInvitation(ctx context.Context, db DBTX, arg GetInvitationParams) (GetInvitationRow, error)
	// GetUser runs the :one query.
	GetUser(ctx context.Context, db DBTX, arg GetUserParams) (GetUserRow, error)
	// ListAccounts runs the :many query.
	ListAccounts(ctx context.Context, db DBTX, arg ListAccountsParams) ([]ListAccountsRow, error)
	// ListInvitations runs the :many query.
	ListInvitations(ctx context.Context, db DBTX, arg ListInvitationsParams) ([]ListInvitationsRow, error)
	// ListUsers runs the :many query.
	ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]ListUsersRow, error)
	// UpdateAccount runs the :execrows query.
	UpdateAccount(ctx context.Context, db DBTX, arg UpdateAccountParams) (int64, error)
	// UpdateUser runs the :execrows query.
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (int64, error)
}
