// Package gogen renders unison's IR as Go source.
//
// It is the one emitter v1 ships, and it sits behind the IR seam so that it
// knows nothing about sqlc, protobufs, or dialect analysis — only about shapes
// and statements.
//
// Two rules govern everything here. The shared files are a pure function of the
// roster, the query shapes, and the options, so that every dialect's invocation
// writes the same bytes to the same paths. And nothing is emitted from a map
// iteration or a clock: regeneration produces identical output or consumers
// cannot gate CI on it.
package gogen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/primandproper/sqlc-gen-unison/internal/ir"
)

// File is one emitted file.
type File struct {
	Name     string
	Contents []byte
}

// Emit renders a package as the files sqlc should write.
//
// Every invocation emits all of them: the shared three and its own dialect's
// one. That redundancy is the design rather than an oversight — it costs
// microseconds and removes an entire merge, hash, and promotion subsystem. When
// the dialects agree the shared writes are byte-identical no-ops; when they do
// not, the last write wins and some other dialect's query file references a
// symbol that is no longer declared, which the Go compiler reports by name.
func Emit(pkg *ir.Package) ([]File, error) {
	files := make([]File, 0, 4)

	for _, emit := range []struct {
		fn   func(*ir.Package) (string, error)
		name string
	}{
		{name: "db.go", fn: emitDB},
		{name: "types.go", fn: emitTypes},
		{name: "querier.go", fn: emitQuerier},
		{name: queriesFilename(pkg.Dialect), fn: emitQueries},
	} {
		source, err := emit.fn(pkg)
		if err != nil {
			return nil, fmt.Errorf("emitting %s: %w", emit.name, err)
		}

		formatted, err := format.Source([]byte(source))
		if err != nil {
			// A generator that emits code go/format cannot parse has a bug, and
			// the useful thing is the source it produced, not the offset.
			return nil, fmt.Errorf("emitting %s: unison produced Go it cannot parse: %w\n%s", emit.name, err, source)
		}

		files = append(files, File{Name: emit.name, Contents: formatted})
	}

	return files, nil
}

// queriesFilename names a dialect's query file.
func queriesFilename(dialect string) string {
	return "queries_" + strings.ToLower(dialect) + ".go"
}

// header is the generated-file banner.
//
// It carries the two versions that identify what produced the file and nothing
// else — no date, no host, no absolute path. Every one of those would make the
// second generation differ from the first.
func header(pkg *ir.Package) string {
	return fmt.Sprintf(`// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   %s
// unison: %s

package %s

`, pkg.SQLCVersion, pkg.UnisonVersion, pkg.Name)
}

// emitDB renders db.go: the executor interface, the dialect enum, and the
// constructor that switches over the roster.
func emitDB(pkg *ir.Package) (string, error) {
	imports := newImportSet()

	imports.add("context")
	imports.add("database/sql")
	imports.add("fmt")

	var b strings.Builder

	b.WriteString(`// DBTX is what a generated method needs from a database handle.
//
// It is satisfied by *sql.DB, *sql.Tx, and *sql.Conn alike, and it is taken per
// call rather than held on the querier so that running a query inside a
// transaction is a different argument rather than a different querier.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// Dialect names a SQL dialect this package was generated for.
//
// It is a type rather than a string so that naming one that was not generated
// is a compile error rather than an error value at startup.
type Dialect string

`)

	b.WriteString("const (\n")

	for _, dialect := range pkg.Roster {
		fmt.Fprintf(&b, "\t// Dialect%s is %s.\n", dialectName(dialect), dialect)
		fmt.Fprintf(&b, "\tDialect%s Dialect = %q\n", dialectName(dialect), dialect)
	}

	b.WriteString(")\n\n")

	b.WriteString("// Dialects lists every dialect this package was generated for, in a stable\n// order.\nfunc Dialects() []Dialect {\n\treturn []Dialect{\n")

	for _, dialect := range pkg.Roster {
		fmt.Fprintf(&b, "\t\tDialect%s,\n", dialectName(dialect))
	}

	b.WriteString("\t}\n}\n\n")

	if pkg.TablePrefix {
		fmt.Fprintf(&b, `// prefixMarker stands where a table name begins in every statement below.
//
// The generator placed it using the analyzer's catalog, so it marks identifiers
// that are genuinely tables rather than words that look like them. New replaces
// it once per statement, at construction; nothing rewrites SQL at query time.
const prefixMarker = %q

`, ir.PrefixMarker)
	}

	b.WriteString(newFunc(pkg))

	return header(pkg) + imports.render() + b.String(), nil
}

// newFunc renders the constructor. Its signature depends on whether the
// consumer asked for prefix markers, and that answer is the same for every
// invocation, so every invocation renders the same function.
func newFunc(pkg *ir.Package) string {
	var b strings.Builder

	signature := "func New(dialect Dialect) (Querier, error) {"
	callArgs := "()"
	doc := `// New returns the Querier for a dialect.
//
// Every dialect in the roster is compiled into this package; a caller
// instantiates the one their database speaks.`

	if pkg.TablePrefix {
		signature = "func New(dialect Dialect, prefix string) (Querier, error) {"
		callArgs = "(prefix)"
		doc = `// New returns the Querier for a dialect, with every table name prefixed.
//
// Every dialect in the roster is compiled into this package; a caller
// instantiates the one their database speaks. The prefix is substituted into
// each statement once, here, and the statements are held ready to run.`
	}

	b.WriteString(doc + "\n" + signature + "\n\tswitch dialect {\n")

	for _, dialect := range pkg.Roster {
		fmt.Fprintf(&b, "\tcase Dialect%s:\n\t\treturn %s%s, nil\n",
			dialectName(dialect), dialectConstructor(dialect), callArgs)
	}

	fmt.Fprintf(&b, "\tdefault:\n\t\treturn nil, fmt.Errorf(%q, dialect)\n\t}\n}\n",
		pkg.Name+": unknown dialect %q")

	return b.String()
}

// emitQuerier renders querier.go: the interface every dialect implements.
func emitQuerier(pkg *ir.Package) (string, error) {
	imports := newImportSet()

	imports.add("context")

	var b strings.Builder

	b.WriteString(`// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
type Querier interface {
`)

	for i := range pkg.Queries {
		query := &pkg.Queries[i]

		signature, err := methodSignature(query, pkg.NullAs, imports)
		if err != nil {
			return "", err
		}

		fmt.Fprintf(&b, "\t// %s runs the %s query.\n", query.Name, query.Command)
		fmt.Fprintf(&b, "\t%s\n", signature)
	}

	b.WriteString("}\n")

	return header(pkg) + imports.render() + b.String(), nil
}

// emitTypes renders types.go: the params and row structs.
func emitTypes(pkg *ir.Package) (string, error) {
	imports := newImportSet()

	var b strings.Builder

	for i := range pkg.Queries {
		query := &pkg.Queries[i]

		if len(query.Params) > 0 {
			fmt.Fprintf(&b, "// %sParams are the arguments to %s.\n", query.Name, query.Name)
			fmt.Fprintf(&b, "type %sParams struct {\n", query.Name)

			if err := writeFields(&b, query.Params, pkg.NullAs, imports); err != nil {
				return "", fmt.Errorf("%s params: %w", query.Name, err)
			}

			b.WriteString("}\n\n")
		}

		if !query.Command.ReturnsRows() {
			continue
		}

		fmt.Fprintf(&b, "// %sRow is one row of %s's result.\n", query.Name, query.Name)
		fmt.Fprintf(&b, "type %sRow struct {\n", query.Name)

		if err := writeFields(&b, query.Columns, pkg.NullAs, imports); err != nil {
			return "", fmt.Errorf("%s row: %w", query.Name, err)
		}

		b.WriteString("}\n\n")
	}

	return header(pkg) + imports.render() + b.String(), nil
}

// writeFields renders struct fields in the order the SQL gives them.
//
// The order is deliberate: a row struct that reads top to bottom like the
// projection it came from is a struct a reviewer can check against the query by
// eye, which is the correspondence §1 says nothing checks today.
func writeFields(b *strings.Builder, fields []ir.Field, nullAs string, imports *importSet) error {
	for i := range fields {
		field := &fields[i]

		rendered, err := goType(field.Type, nullAs, imports)
		if err != nil {
			return err
		}

		fmt.Fprintf(b, "\t%s %s\n", exportedName(field.Name), rendered)
	}

	return nil
}

// methodSignature renders one query's signature, shared by the interface and
// every dialect's implementation of it.
func methodSignature(query *ir.Query, nullAs string, imports *importSet) (string, error) {
	args := "ctx context.Context, db DBTX"
	if len(query.Params) > 0 {
		args += fmt.Sprintf(", arg %sParams", query.Name)
	}

	results, err := methodResults(query, nullAs, imports)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%s(%s) %s", query.Name, args, results), nil
}

// methodResults renders a query's return types.
func methodResults(query *ir.Query, _ string, imports *importSet) (string, error) {
	switch query.Command {
	case ir.CommandExec:
		return "error", nil
	case ir.CommandExecRows:
		return "(int64, error)", nil
	case ir.CommandExecResult:
		imports.add("database/sql")

		return "(sql.Result, error)", nil
	case ir.CommandOne:
		return fmt.Sprintf("(%sRow, error)", query.Name), nil
	case ir.CommandMany:
		return fmt.Sprintf("([]%sRow, error)", query.Name), nil
	case ir.CommandInvalid:
		return "", fmt.Errorf("query %s has no command", query.Name)
	default:
		return "", fmt.Errorf("query %s has an unknown command", query.Name)
	}
}
