package generate_test

import (
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/shoenig/test"
	"github.com/shoenig/test/must"
)

// update rewrites the golden files instead of comparing against them.
//
//	go test ./internal/generate/ -update
//
//nolint:gochecknoglobals // a test flag has nowhere else to live.
var update = flag.Bool("update", false, "rewrite the golden files from the current output")

// goldenDir holds the emitted package for the corpus, committed so that a change
// in what unison emits shows up in review as a diff of Go rather than as a
// number in a test name.
const goldenDir = "../../testdata/golden/identitydb"

// TestGolden compares the emitted package against the committed one.
//
// This is §11's golden-file test, and it earns its keep in review rather than in
// CI: the compile tests already prove the output is valid and convergent, but
// only a diff shows a human that a header moved, a scan order changed, or a
// method signature grew an argument.
func TestGolden(t *testing.T) {
	t.Parallel()

	emitted := readAll(t, corpus{}.generate(t))

	if *update {
		must.NoError(t, os.RemoveAll(goldenDir))
		must.NoError(t, os.MkdirAll(goldenDir, 0o750))

		for name, contents := range emitted {
			must.NoError(t, os.WriteFile(filepath.Join(goldenDir, name), []byte(contents), 0o600))
		}

		t.Log("golden files rewritten; review the diff before committing")

		return
	}

	golden := readAll(t, goldenDir)

	// Compared as whole maps so that an unexpected extra file is a failure too,
	// not just a changed one.
	must.Eq(t, golden, emitted,
		must.Sprint("the emitted package differs from the golden files; re-run with -update and review the diff"))
}

// TestGoldenIsReadable is a small guard on the one exit criterion no assertion
// can really carry: that someone who has never heard of this tool can read the
// output.
//
// It checks the things a reader would first look for — that every file says what
// generated it, that the shared types are documented, and that no absolute path
// from the machine that generated them leaked into the header.
func TestGoldenIsReadable(t *testing.T) {
	t.Parallel()

	golden := readAll(t, goldenDir)

	must.MapNotEmpty(t, golden)

	for name, contents := range golden {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			test.StrContains(t, contents, "// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.")
			test.StrContains(t, contents, "package identitydb")

			// Nothing that would differ between two machines or two runs.
			test.StrNotContains(t, contents, "/Users/")
			test.StrNotContains(t, contents, "/tmp/")
			test.StrNotContains(t, contents, "/var/folders/")
		})
	}
}
